### ISSUE TITLE
Is not the Facade a singleton?

### ISSUE THREAD

**Issue by Ducasse** [hernanmd/the-note-taker#1]
I have the impression that this is a better name.
In addition in the future we can imagine that the notes are saved on disc and loaded and we could have multiple groups of notes.
But I do not want to dream just get something working with simple scenario.

**Comment by hernanmd** [comment]
I was thinking about the same. The simplest solution works for me so I will update it.

**Comment by hernanmd** [comment]
Now using a Singleton :)
