### ISSUE TITLE
Why do we have isValidNoteTitle: duplicated?

### ISSUE THREAD

**Issue by Ducasse** [hernanmd/the-note-taker#19]
```
isValidNoteTitle: aString 
	"Answer <true> if aString is a valid note title"
	
	^ self application isValidNoteTitle: aString
```

I do not really understand the title in the name of the method.

**Comment by hernanmd** [comment]
You're right, it should be renamed to "name", the title is only for UI purposes.
So we should have `isValidNoteName:` and so on.
